-- school_year
INSERT INTO school_year VALUES
(NULL, 'Gyps fulvus', '2001/1/1', '2002/1/1'),
(NULL, 'Nyctereutes procyonoides', '2002/1/1', '2003/1/1'),
(NULL, 'Isoodon obesulus', '2003/1/1', '2004/1/1');

-- usr
INSERT INTO usr VALUES
(NULL, 'nstollenhof0@paginegialle.it', '["ROLE_STUDENT"]', 'rzeuR1nS', 'Nonie', 'Stollenhof', '469-296-1196', 2),
(NULL, 'rdegregorio1@independent.co.uk', '["ROLE_STUDENT"]', 'r6xQR4', 'Roz', 'De Gregorio', '502-852-5198', 2),
(NULL, 'dminchell2@google.co.uk', '["ROLE_STUDENT"]', 'h0Fvu34WEhvg', 'Dewie', 'Minchell', '839-215-9373', 2),
(NULL, 'akempson3@about.com', '["ROLE_STUDENT"]', 'opjeNH94Y', 'Abby', 'Kempson', '305-506-3016', 1),
(NULL, 'tcardew4@ezinearticles.com', '["ROLE_STUDENT"]', 'MPQyJcVmUWe', 'Teresita', 'Cardew', '229-201-6301', 3),
(NULL, 'eolsen5@gmpg.org', '["ROLE_STUDENT"]', 'disFzEm', 'Ellyn', 'Olsen', '963-196-1179', 2),
(NULL, 'kpursglove6@dell.com', '["ROLE_STUDENT"]', 'IZIx1X', 'Kattie', 'Pursglove', '727-705-1747', 3),
(NULL, 'ppiggford7@oracle.com', '["ROLE_STUDENT"]', 'qA4Ur2', 'Pinchas', 'Piggford', '183-295-1021', 3),
(NULL, 'dvankeev8@opera.com', '["ROLE_STUDENT"]', 'Bn234rUxpK5s', 'Dante', 'Vankeev', '379-239-7260', 1),
(NULL, 'ahuglin9@cdbaby.com', '["ROLE_STUDENT"]', 'jdABMaWaK26T', 'Alberik', 'Huglin', '158-473-4315', 2),
(NULL, 'gparmera@abc.net.au', '["ROLE_STUDENT"]', 'o8F7HPLwau', 'Gerhard', 'Parmer', '508-293-9874', 1),
(NULL, 'gpogsonb@thetimes.co.uk', '["ROLE_STUDENT"]', 'SG8PgqsCc', 'Grier', 'Pogson', '881-506-3987', 1),
(NULL, 'vbulbeckc@csmonitor.com', '["ROLE_STUDENT"]', '8gsGuNblpyW', 'Vivianna', 'Bulbeck', '654-508-3126', 1),
(NULL, 'hkarpetsd@ebay.com', '["ROLE_STUDENT"]', 'aKjo3QJsCO', 'Hogan', 'Karpets', '994-428-1148', 2),
(NULL, 'nmidnere@ucla.edu', '["ROLE_STUDENT"]', 'fvXJ5pep84', 'Nolan', 'Midner', '506-172-2420', 2),
(NULL, 'skinceyf@woothemes.com', '["ROLE_STUDENT"]', 'P18pU6xID', 'Sidonia', 'Kincey', '254-191-9409', 2),
(NULL, 'afrillg@mashable.com', '["ROLE_STUDENT"]', 'Zh7cr0WMBxi', 'Anderea', 'Frill', '240-239-2338', 2),
(NULL, 'wipgraveh@cornell.edu', '["ROLE_STUDENT"]', 'NbSZlbJ53uF', 'Welsh', 'Ipgrave', '555-828-7900', 1),
(NULL, 'loughtoni@indiegogo.com', '["ROLE_STUDENT"]', 'y917lH7XDn3', 'Leyla', 'Oughton', '282-681-5917', 2),
(NULL, 'jgeraultj@fc2.com', '["ROLE_STUDENT"]', 'Q33RcGAJ', 'Jervis', 'Gerault', '590-972-8740', 2),
(NULL, 'wstraneok@sciencedaily.com', '["ROLE_STUDENT"]', '8JJeUqxVw5', 'Wolfie', 'Straneo', '577-669-5532', 2),
(NULL, 'wmacrannelll@typepad.com', '["ROLE_STUDENT"]', 'VSbpmr', 'Wright', 'MacRannell', '313-441-6530', 3),
(NULL, 'tsamplem@is.gd', '["ROLE_STUDENT"]', 'wB8uLd', 'Tallou', 'Sample', '254-231-8493', 2),
(NULL, 'pjewissn@bandcamp.com', '["ROLE_STUDENT"]', 'zyG9xm6bp', 'Padriac', 'Jewiss', '184-488-6674', 1),
(NULL, 'hcowopeo@ezinearticles.com', '["ROLE_STUDENT"]', 'e2s7gWl', 'Harcourt', 'Cowope', '873-942-1680', 2),
(NULL, 'kpitbladdop@wufoo.com', '["ROLE_STUDENT"]', 'IlTtThyexaNl', 'Kaitlin', 'Pitbladdo', '701-846-4775', 1),
(NULL, 'cfollosq@amazonaws.com', '["ROLE_STUDENT"]', 'ILoX6w', 'Cari', 'Follos', '641-319-8096', 1),
(NULL, 'amccrillisr@elegantthemes.com', '["ROLE_STUDENT"]', 'mD2Q6TQ', 'Adiana', 'McCrillis', '847-144-1257', 1),
(NULL, 'akestevens@usatoday.com', '["ROLE_STUDENT"]', 'iHBdI2', 'Agathe', 'Kesteven', '659-779-5384', 1),
(NULL, 'dfritschelt@indiatimes.com', '["ROLE_STUDENT"]', 'Syl5fGiHyAWr', 'Dani', 'Fritschel', '188-612-8905', 2),
(NULL, 'rbullivantu@so-net.ne.jp', '["ROLE_STUDENT"]', 'R655AFY0WCYU', 'Rachele', 'Bullivant', '213-526-2624', 1),
(NULL, 'ssiddelev@smh.com.au', '["ROLE_STUDENT"]', 'Hkoh6mFpKC1', 'Sophie', 'Siddele', '427-920-0687', 1),
(NULL, 'zkoppsw@miibeian.gov.cn', '["ROLE_STUDENT"]', 'EKk6NfzLTdo', 'Zarla', 'Kopps', '541-449-3209', 1),
(NULL, 'lgarnhamx@hatena.ne.jp', '["ROLE_STUDENT"]', 'DDl379x5xg', 'Liam', 'Garnham', '575-261-9155', 3),
(NULL, 'bansticey@marriott.com', '["ROLE_STUDENT"]', 'Rmgk3Rre', 'Berenice', 'Anstice', '336-818-7560', 1),
(NULL, 'tpinnionz@pbs.org', '["ROLE_STUDENT"]', 'xU2err', 'Teador', 'Pinnion', '525-893-7098', 2),
(NULL, 'sdimberline10@ebay.co.uk', '["ROLE_STUDENT"]', 'ZgJXj4B4G', 'Sean', 'Dimberline', '883-447-1736', 3),
(NULL, 'ddachs11@artisteer.com', '["ROLE_STUDENT"]', 'EKYceh', 'Dorian', 'Dachs', '750-903-1345', 1),
(NULL, 'mcripwell12@naver.com', '["ROLE_STUDENT"]', 'SVwdGqvCNC', 'Milty', 'Cripwell', '824-749-5863', 1),
(NULL, 'vmariyushkin13@auda.org.au', '["ROLE_STUDENT"]', '0vMzQAO', 'Vincents', 'Mariyushkin', '260-663-6221', 2),
(NULL, 'gtaplow14@github.com', '["ROLE_STUDENT"]', 'b17fDrH4awz', 'Gar', 'Taplow', '685-225-7160', 2),
(NULL, 'dgoning15@elegantthemes.com', '["ROLE_STUDENT"]', 'CsrgNZcAZ1O', 'Dorey', 'Goning', '330-966-9947', 2),
(NULL, 'acortez16@lulu.com', '["ROLE_STUDENT"]', 'XVcA89KOhk', 'Allyson', 'Cortez', '556-995-3376', 2),
(NULL, 'acrunden17@comsenz.com', '["ROLE_STUDENT"]', '86eepVpTBh', 'Alessandro', 'Crunden', '526-947-6882', 1),
(NULL, 'rhurleston18@spotify.com', '["ROLE_STUDENT"]', 'Qq1Q6ZjI', 'Rachael', 'Hurleston', '249-388-4024', 2),
(NULL, 'fwemyss19@360.cn', '["ROLE_STUDENT"]', 'xLXUf0', 'Frazer', 'Wemyss', '656-418-3844', 2),
(NULL, 'bgherarducci1a@engadget.com', '["ROLE_STUDENT"]', 'oKMKOhi9tZKz', 'Blair', 'Gherarducci', '642-550-4210', 3),
(NULL, 'vgrice1b@loc.gov', '["ROLE_STUDENT"]', 'TCEztSyA9W', 'Valle', 'Grice', '179-138-9359', 2),
(NULL, 'piwaszkiewicz1c@shop-pro.jp', '["ROLE_STUDENT"]', 'tFFJQu4Er', 'Pauly', 'Iwaszkiewicz', '608-768-7020', 1),
(NULL, 'krandalson1d@mozilla.org', '["ROLE_STUDENT"]', 'ulcFjQ', 'Ky', 'Randalson', '862-168-2541', 2),
(NULL, 'mdommersen1e@narod.ru', '["ROLE_STUDENT"]', 'kZxX4CF', 'Mozelle', 'Dommersen', '639-382-1708', 1),
(NULL, 'awaterhowse1f@technorati.com', '["ROLE_STUDENT"]', 'kumu6cI', 'Adeline', 'Waterhowse', '376-474-4870', 1),
(NULL, 'ccartin1g@adobe.com', '["ROLE_STUDENT"]', 'MB4FKs', 'Courtenay', 'Cartin', '224-839-9253', 3),
(NULL, 'aditch1h@skype.com', '["ROLE_STUDENT"]', 'xCsFom', 'Audre', 'Ditch', '517-974-3644', 3),
(NULL, 'gbarkhouse1i@washingtonpost.com', '["ROLE_STUDENT"]', 'GCp0SrsDUZzB', 'Gilbert', 'Barkhouse', '807-478-1217', 1),
(NULL, 'cmckilroe1j@shinystat.com', '["ROLE_STUDENT"]', 'VPtOC08Ew', 'Charo', 'McKilroe', '434-597-8423', 3),
(NULL, 'pwodeland1k@merriam-webster.com', '["ROLE_STUDENT"]', 'QE9BXTuxuFM', 'Philipa', 'Wodeland', '274-552-8386', 3),
(NULL, 'edebruijn1l@samsung.com', '["ROLE_STUDENT"]', 'Z0EBM4zyU', 'Evin', 'De Bruijn', '290-546-9660', 2),
(NULL, 'garmor1m@arstechnica.com', '["ROLE_STUDENT"]', 'MNgDotaP', 'Germana', 'Armor', '548-675-5517', 1),
(NULL, 'dmcarthur1n@princeton.edu', '["ROLE_STUDENT"]', '6PbyGoiT7OZ', 'Darelle', 'McArthur', '336-874-1636', 3),

(NULL, 'gbladen0@whitehouse.gov', '["ROLE_TEACHER"]', 'zbC9wZx', 'Glad', 'Bladen', '8464797855', NULL),
(NULL, 'fdegoe1@reference.com', '["ROLE_TEACHER"]', 'anwzfOEo2n', 'Frazier', 'Degoe', '2442948519', NULL),
(NULL, 'dbolding2@yelp.com', '["ROLE_TEACHER"]', 'd3MIYVmLhFwd', 'Dido', 'Bolding', '3318233655', NULL),
(NULL, 'jgimson3@about.me', '["ROLE_TEACHER"]', 'Jt7xczwJ', 'Jorgan', 'Gimson', '3964202144', NULL),
(NULL, 'oprover4@rakuten.co.jp', '["ROLE_TEACHER"]', 'Cm8N0uymc', 'Orrin', 'Prover', '4977819265', NULL),

(NULL, 'swoller0@usgs.gov', '["ROLE_CLIENT"]', 'jCjLk1n9', 'Sauncho', 'Woller', '5793922648', NULL),
(NULL, 'rcrilly1@mit.edu', '["ROLE_CLIENT"]', 'nqoXLoT', 'Rawley', 'Crilly', '6831878821', NULL),
(NULL, 'hroches2@merriam-webster.com', '["ROLE_CLIENT"]', 'KLRu7CIOZf', 'Hildegarde', 'Roches', '7409284260', NULL),
(NULL, 'bdeavenell3@smh.com.au', '["ROLE_CLIENT"]', 'wkpQ4f', 'Beckie', 'De Avenell', '6692927169', NULL),
(NULL, 'btommasi4@google.fr', '["ROLE_CLIENT"]', 'mMTwxsgdtI', 'Batholomew', 'Tommasi', '5481368227', NULL),
(NULL, 'nshovelton5@purevolume.com', '["ROLE_CLIENT"]', 'h3FqQkmTu', 'Nadean', 'Shovelton', '9226291244', NULL),
(NULL, 'gcollinge6@meetup.com', '["ROLE_CLIENT"]', '3Y2VXFadO3', 'Giacinta', 'Collinge', '9322540917', NULL),
(NULL, 'hclayton7@sourceforge.net', '["ROLE_CLIENT"]', 'STJyqcOT8', 'Humbert', 'Clayton', '7664595036', NULL),
(NULL, 'kkeeves8@mozilla.com', '["ROLE_CLIENT"]', 'QsAm10xL4sg', 'Klaus', 'Keeves', '9393447697', NULL),
(NULL, 'kjosselson9@vimeo.com', '["ROLE_CLIENT"]', '59FLNSiWN93', 'Krishna', 'Josselson', '7488436625', NULL),
(NULL, 'loverila@imageshack.us', '["ROLE_CLIENT"]', 'pk5DczDN', 'Lalo', 'Overil', '9018770313', NULL),
(NULL, 'bpaylorb@histats.com', '["ROLE_CLIENT"]', 'uygv68iR', 'Barnett', 'Paylor', '6119079482', NULL),
(NULL, 'vgilmartinc@newyorker.com', '["ROLE_CLIENT"]', 'BrF1R0VUbo2', 'Vivienne', 'Gilmartin', '4155764355', NULL),
(NULL, 'jbarbeyd@about.me', '["ROLE_CLIENT"]', 'ZvTxCmAprdE4', 'Jacinda', 'Barbey', '1905322612', NULL),
(NULL, 'whallitte@ustream.tv', '["ROLE_CLIENT"]', 'S0JzfPcvodtb', 'Worth', 'Hallitt', '5105490579', NULL);

-- project
INSERT INTO project VALUES
(NULL, 'Twimbo', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'),
(NULL, 'Yotz', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.'),
(NULL, 'Jaxspan', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.'),
(NULL, 'Fiveclub', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.'),
(NULL, 'Dynazzy', 'Morbi porttitor lorem id ligula.'),
(NULL, 'Riffpath', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.'),
(NULL, 'Skipfire', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.'),
(NULL, 'Cogibox', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.'),
(NULL, 'Gabspot', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.'),
(NULL, 'Photolist', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.'),
(NULL, 'Centidel', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.'),
(NULL, 'Oyope', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.'),
(NULL, 'Mydeo', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.'),
(NULL, 'Dazzlesphere', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'),
(NULL, 'Plajo', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam. Suspendisse potenti.'),
(NULL, 'Agimba', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam.'),
(NULL, 'Teklist', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.'),
(NULL, 'Edgetag', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.'),
(NULL, 'Quinu', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.'),
(NULL, 'Oyope', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.')